name: Build and deploy Node.js app to Azure Web App - UniMedia

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build
        run: |
          cd frontend/frontend-react
          npm install
          npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: frontend/frontend-react/build/**/*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Prepare deployment directory
        run: mkdir -p deployment

      - name: Unzip artifact for deployment
        run: unzip node-app -d deployment

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'UniMedia'
          slot-name: 'Production'
          package: deployment
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EBD15802392C4A31AE8E44CBC1189D69 }}
